[project]
name = "spark-classification-algorithms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.2",
    "psutil>=7.0.0",
    "pyspark>=4.0.0",
    "scikit-learn>=1.7.1",
]
